# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "69ac83d1e0a2e7f43359940d973ecd1c"
name = "back-to-top"
handle = "back-to-top-10"
application_url = "https://included-truly-artificial-trips.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://included-truly-artificial-trips.trycloudflare.com/auth/callback",
  "https://included-truly-artificial-trips.trycloudflare.com/auth/shopify/callback",
  "https://included-truly-artificial-trips.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
